### ISSUE TITLE
Marketing API not adding/updating list member tags

### ISSUE THREAD

**Issue by BladeFrisch** [mailchimp/mailchimp-client-lib-codegen#23] opened 2020-08-26 00:39 UTC
I am trying to add a new tag to a list member using the NodeJS API, and the tag is not being added. I am also trying to update a tag status from active to inactive in another portion of the code, and that is also not working. This is done in a cloud function on Firebase using the following code snippet:

```javascript
mailchimp.lists.updateListMemberTags(listID, emailHash, {
  tags: [{name: "Test New Tag", status: "active"}]
})
.then((response) => {
  console.log(response);
  return res.send(response);
})
.catch((err) => {
  console.log(err);
  return res.send(err);
});
```

I am able to read existing tags using the function call `mailchimp.lists.getListMemberTags(listID, emailHash)`, but this is the only tags related call that is working. I am able to perform other member management tasks using the new API, but not the tag adding or updating.

**Comment by BladeFrisch** [comment] 2020-09-01 20:09
I just tried using cURL in git bash to see if that will add a tag, and the following command worked.

```curl
curl --request POST --url https://us20.api.mailchimp.com/3.0/lists/{listId}/members/{userHash}/tags --user "foo:{apiKey}" --include --data '{"tags":[{"name": "Test New Tag", "status": "active"}]}'
```

It appears that the error is with the NodeJS call to the API. Is there something wrong with how I'm calling the API function in the above message?

**Comment by scodeler** [comment] 2020-09-24 20:32
@BladeFrisch I can't manage to update the tags either.
Docs are confusing, I think the correct way is to pass an array of objects with the structure `{ name, status }`, but mine is not working as well... so, who knows....

**Comment by lumpysimon** [comment] 2020-12-10 12:20
The PHP example [on this page](https://mailchimp.com/developer/guides/organize-contacts-with-tags/#label-a-contact-with-a-tag) for adding tags to a member doesn't seem to work, I'm getting a `400 Bad Request` response with an `Invalid Resource` title.

Here's the code from the docs:

```
$mailchimp->lists->updateListMemberTags($list_id, $subscriber_hash, [
    "tags" => [
      "name" => "Influencer",
      "status" => "active"
    ]
  ]);
```

My `$list_id` and `$subscriber_hash` are both correct, as they are exactly the same as I use in the preceding `setListMember` call, which works fine.

And the PHP code in [the API reference for updateListMemberTags](https://mailchimp.com/developer/api/marketing/list-member-tags/add-or-remove-member-tags/) doesn't include the body part at all:

```
$response = $client->lists->updateListMemberTags("list_id", "subscriber_hash");
```

**Comment by lumpysimon** [comment] 2020-12-10 12:37
Ah, I've figured out what the problem is: the example code has one level of array missing (there needs to be another array within the `tags` array):

```
$mailchimp->lists->updateListMemberTags($list_id, $subscriber_hash, [
    "tags" => [
        [
             "name" => "Influencer",
             "status" => "active"
        ]
    ]
  ]);
```

Can you please correct the 'Organize Contacts with Tags' page and add in the body on the 'updateListMemberTags' reference example?

**Comment by alexmarple** [comment] 2020-12-21 18:35
@lumpysimon and @scodeler and @BladeFrisch. Updated the guides. Can you confirm it is now working for you?

**Comment by Kerumen** [comment] 2020-12-31 00:01
@mtashley 

I've run into that problem also. Why this function needs the `body` key but the other don't? (on Node.js)

**Comment by lumpysimon** [comment] 2020-12-31 12:23
> Updated the guides. Can you confirm it is now working for you?

Thanks @alexmarple all looks good now :)

**Comment by BladeFrisch** [comment] 2021-01-14 21:13
@alexmarple my apologies for the delay. The documentation is still incorrect, but I found out what the issue is. The main issue with the documentation is the nested arrays in the "tags" field, seen in the screenshot attached. When I tried to run the snippet from the documentation, I received an error message saying "tags[0].name cannot be blank". When I removed one of the array levels to make sure that tags[0] would give the JSON object, things worked perfectly:

```js
mailchimp.lists.updateListMemberTags(
    listId,
    emailHash,
    {
      body: {
        tags: [          
            {
              name: "Test Tag",
              status: "active"
            }          
        ]
      }
    }
  )
```
The node.js documentation would need that nested array removed, and then it's great.

![1](https://user-images.githubusercontent.com/50836373/104649517-dab58b00-5682-11eb-8ce0-a8549b5a79de.png)'

**Comment by BladeFrisch** [comment] 2021-01-15 19:17
After doing some further development last night and today, the node.js API inexplicably stopped working. I am receiving no error messages, the responses from the updateListMemberTags() call is exactly what I expected, but the tag is not showing up on the MailChimp dashboard.
I assume this is related to updating another package and/or dependency, or perhaps a cross-compatibility issue with another package (I did install and start development with the MailChimp Transactional API that has an axios dependcy). If I checkout the previous commit I made at the time of my previous comment on this issue, things still work as intended and tags are added. I am working on pinpointing the exact update(s) and/or package(s) where things stop working and will post another comment once I uncover that point.

**Comment by frankps** [comment] 2021-01-17 09:50
There must be a problem with MailChimp's API: updateListMemberTags(...) used to work, but is NOT working anymore. Since Friday it always returns null. No error, just null.

**Comment by BladeFrisch** [comment] 2021-01-19 04:19
So I did some further exploring today.
My project was initially using version 3.0.13, so I rolled back to that version and incrementally moved up the version numbers. I stopped seeing the tags update when I went from version 3.0.23 to 3.0.24. However, when I rolled back to 3.0.23 (uninstalled the package and reinstalled the specific version number), I was still not able to see the tags update. I even rolled back to 3.0.13 to see if the original version would work. Still nothing.
Throughout this process, I was using just one email to test this. I would remove the tag and archive the contact after each test with the thought of knowing it was working if I would see the email in my main contact list. Is there some limit concerning the number of times you can either call the API in general or modify a specific tag? This process spanned a couple of hours, as I would have to uninstall, reinstall, deploy, and test, so it's not like the tests were happening within seconds of each other. There was probably a 5 minute average between tests, perhaps longer as I was working on other things as well.

**Comment by nourmalaeb** [comment] 2021-01-19 23:54
I just filed a new issue for this before seeing this one... I couldn't get the API to work until I removed the body wrapper from the request body.

This is what's in the docs:

```javascript
const response = await mailchimp.lists.updateListMemberTags(
    listId,
    subscriberHash,
    {
      body: {
        tags: [
          [
            {
              name: "Influencer",
              status: "active",
            },          
          ],
        ],
      },
    }
  );
```

This is what worked:

```javascript
const response = await mailchimp.lists.updateListMemberTags(
    listId,
    subscriberHash,
    // remove { body: } wrapper
    {
      tags: {
          [
            {
              name: "Influencer",
              status: "active",
            },          
          ],
      },
    }
  );
```

Seems like the docs need to be updated. Tags are probably broken for a lot of folks right now.

**Comment by BladeFrisch** [comment] 2021-01-20 01:16
@nourmalaeb What version of the API are you using? Because mine was NOT working without the body tag when I originally filed this issue using 3.0.13. I'll try it now with the latest version without the body tag to see what happens. These docs are definitely confusing and in some places outright conflicting. They need to be cleaned up a bit to reflect what actually needs to happen.

**Comment by nourmalaeb** [comment] 2021-01-20 12:16
Oh good point, I'm using 3.0.27

**Comment by BladeFrisch** [comment] 2021-01-20 23:08
@bipol-mc that did it!! Thank you so much! I was trying to find the right file to look for the diff between versions but I just don't have enough familiarity with the source code to do that.
Thanks again! I'm fine with closing this issue if everything is cleared on your end.

**Comment by bipol-mc** [comment] 2021-01-21 13:05
@BladeFrisch great!  Our [docs](https://mailchimp.com/developer/marketing/guides/organize-contacts-with-tags/#label-a-contact-with-a-tag) should be updated now as well.  Thanks for the help y'all, closing the issue.

**Closed by bipol-mc** 2021-01-21 13:05 UTC
Labels: marketing-node

**Comment by Kerumen** [comment] 2021-01-21 13:35
@bipol-mc Thanks! Could you also update the [docs here](https://mailchimp.com/developer/marketing/api/list-member-tags/add-or-remove-member-tags/)?

![Screenshot 2021-01-21 at 14 35 02](https://user-images.githubusercontent.com/5436545/105357979-db579f80-5bf5-11eb-892b-231455a72dc4.png)

The body parameter of the example should not be `{}`.

**Comment by bipol-mc** [comment] 2021-01-21 15:31
@Kerumen - ah, good point!  

This is unfortunately a side effect of a bug we're having with our code sample generator for the reference documentation.  The code samples for our guides (e.g. [Organize Contacts with Tags](https://mailchimp.com/developer/marketing/guides/organize-contacts-with-tags/#label-a-contact-with-a-tag)) are written by hand, so I was able to do a simple update to a static page for that.  I'll definitely be looking into this rendering issue though!

**Comment by alexmarple** [comment] 2021-01-21 15:34
@bipol-mc I can update the docs. 

Sorry I'm late to the party and thank you for everyone who triaged this. I will look over this and make corrections to the docs as soon as I can!

**Comment by frankps** [comment] 2021-01-24 16:26
Documentation is still wrong at this moment. 

Can this method also return some kind of valid response? Currently, it's just returning null when it is working.
Last week it was also returning null when not working.
=> we have no idea if this method is working or not!
